apiVersion: v1
kind: Service
metadata:
  name: cleanarch-api-svc
  namespace: cleanarch
spec:
  type: ClusterIP
  selector:
    app: cleanarch-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
